/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function parse(data: string): Person
export class Person {
  name: string
  phones: Array<string>
  constructor(name: string, phones: Array<string>)
}
